### ISSUE TITLE
Errors in new _formtastic_sass

### ISSUE THREAD

**Issue by resistorsoftware** [activestylus/formtastic-sass#5]
=float-inputs-for(!dom_target,!margin_right=10px,!line_height=150%)
  #{!dom_target}
    +float-inputs-core(!margin_right,!line_height)

float-inputs-core???  should that not be floats-inputs-for

and is there not a way to introduce some sort of stack-form-for('#element_id') so that I can target specific forms with specific styles? 

If I change line 418 to float-inputs-for the sass compiler chokes about syntax nesting too deep

**Comment by activestylus** [comment]
To target elements for styling just do:

#my-div
  +stack-form

or

#my-other-div
  +float-form

float inputs core is in internal mixin which is used to DRY up the code a bit - you shouldnt be using it at all

**Comment by activestylus** [comment]
dammit i really need to get up to speed with markdown so it dont eat my code like that

<pre>#my-div
  +stack-form</pre>

**Comment by activestylus** [comment]
Closing.
